version: "3"
services:
  api:
    build: ./server
    volumes:
      - ./server:/code
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: "UTC"

    depends_on:
      - postgres
    #   - executer
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front/index.html:/usr/share/nginx/html/index.html
      - ./front/static/:/usr/share/nginx/html/static/
      - /tmp/nginx_log:/var/log/nginx  # Output log to host
    links:
      - api
    environment:
      TZ: "UTC"
    command: nginx -c /etc/nginx/nginx.conf

  # executer:
  #   # only for build
  #   build: ./executer
  #   command: echo "shellgei executer already initialized"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - nginx
    environment:
      STAGE: local
      #STAGE: production
      DOMAINS: 'localhost -> http://nginx:80'
      #DOMAINS: 'shellgei-web.net -> http://nginx:80, www.shellgei-web.net -> http://nginx:80'

  
  postgres:
    build: db
    environment:
      POSTGRES_USER: "sgweb"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "pgdata:/var/lib/postgresql/data"


volumes:
  pgdata:
    driver: "local"
