# Generated by Django 3.0.3 on 2020-02-22 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('33b5eb6e-0c63-49b1-abca-fe15ae52ff87'), unique=True),
        ),
    ]
