# Generated by Django 3.0.3 on 2020-02-22 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200222_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a3b528ca-fb04-4e10-8cb3-4376751a37a6'), unique=True),
        ),
    ]
