# Generated by Django 3.0.3 on 2020-03-22 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7ecb4011-c001-40ee-881f-c95c401da4f5'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c278323f-8578-4cb2-a6af-6b04bdfb8608'), primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('executed', models.BooleanField(default=False)),
                ('result_stdout', models.TextField(blank=True, null=True)),
                ('result_stderr', models.TextField(blank=True, null=True)),
                ('result_image', models.ImageField(null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='post.Tag')),
            ],
        ),
    ]
