# Generated by Django 3.0.3 on 2020-03-22 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea8322bd-d280-4537-952f-d586861c98fa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8c97f05-9b32-4b65-9912-8a51a27b26b9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
