# Generated by Django 3.0.3 on 2020-03-22 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200322_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74e62b32-ecc0-4011-ab4b-67b74ace1bfa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6848d730-77d7-4821-a2f7-3b8b1e44829e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
