# Generated by Django 3.0.3 on 2020-03-22 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200322_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e267a777-2fb4-440d-aa63-2c83863366f4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afb84070-aec2-417b-8829-b9ff4d480cd2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
