# Generated by Django 3.0.3 on 2020-03-22 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200322_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56cb0f9a-697c-4d44-b5cf-26ef0f3fe75d'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e632f8b8-ac6e-4c42-9d18-fb5006ef04ad'), primary_key=True, serialize=False, unique=True),
        ),
    ]
