# Generated by Django 3.0.3 on 2020-03-22 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200322_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab88b7f5-67d7-4561-914d-a0a486f735b4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a245c8c-9efb-4cdd-822c-5dad586bce52'), primary_key=True, serialize=False, unique=True),
        ),
    ]
