# Generated by Django 3.0.3 on 2020-03-22 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200322_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79f91e27-cf05-4093-8e02-a104191f6ee7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9615bb48-80e2-401d-9c3e-f73f723c3718'), primary_key=True, serialize=False, unique=True),
        ),
    ]
