# Generated by Django 3.0.3 on 2020-03-22 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200322_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4e28d8f-d1de-44bd-bb6c-cf66f601ad71'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bc4b604-bd3a-46d8-a814-0e092a3a5025'), primary_key=True, serialize=False, unique=True),
        ),
    ]
