# Generated by Django 3.0.3 on 2020-03-22 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200322_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f3170df-0df3-48f7-9653-b318d350dfd2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1624c9d1-0322-479e-994c-ac8318491849'), primary_key=True, serialize=False, unique=True),
        ),
    ]
