# Generated by Django 3.0.3 on 2020-03-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200322_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb5724d0-c0c6-4291-9480-479d08e510fc'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ae4cdcb-2b8f-4d3a-bf41-1813d283f5b4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
