# Generated by Django 3.0.3 on 2020-03-22 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200322_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc66d501-9812-4c50-a8d3-0d39345a26b1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49c64860-a649-4353-a423-32e1c222aedf'), primary_key=True, serialize=False, unique=True),
        ),
    ]
